stages:
  preprocess:
    cmd: python code/datasets/preprocessing.py --input data/raw/data_raw.csv --output-dir data/processed
    deps:
      - code/datasets/preprocessing.py
      - data/raw/data_raw.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv
  train:
    cmd: python code/models/training.py --train-data data/processed/train.csv --test-data data/processed/test.csv --output-model-dir models
    deps:
      - code/models/feature_engineering.py
      - code/models/training.py
      - data/processed/train.csv
      - data/processed/test.csv
    outs:
      - models/catboost_model.cbm
      - models/catboost_model.pkl
      - models/model_features.json
